from dataclasses import dataclass
import sys
import logging

logger = logging.getLogger(__name__)

@dataclass 
class RulesMarkdown:
    header: str
    table: str
    footer: str

class Markdown:
    def __init__(self):
        self.header = """
# Rules
This file contains the auto-generated rules and their respective statuses for the different stages of the DaC pipeline.
Do not edit this file by hand, it will be overwritten.

## Results

<br>

"""
        self.footer = """

<br>
---

"""
        return

    def generate(self, data):
        table = """
| Name | Type | Lint |
|:----:|:----:|:----:|
"""
        for ruleResult in data:
            name = f"[{ruleResult.name}](../.{ruleResult.path})"
            rule_type = ruleResult.rule_type
            lint = ruleResult.lint
            table += f"|{name}|{rule_type}|{lint}|\n"

        return RulesMarkdown(
            header=self.header,
            table=table,
            footer=self.footer
        )

    def write(self, markdown, path):
        logger.debug(f"Attempting to write generated rule status file to [{path}]")
        with open(path, "w") as f:
            f.write(markdown.header)
            f.write(markdown.table)
            f.write(markdown.footer)
        logger.info(f"Wrote rule CI status to [{path}]")

if __name__ == "__main__":
    print("[!] -> This module is meant to be imported")
    sys.exit(1)

